config/routes.rb
Rails.application.routes.draw do
  root to: 'surveys#index'
  resources :surveys do
    resources :questions
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :survey
end

app/models/survey.rb
class Survey < ApplicationRecord
  has_many :questions, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def new
    @survey = Survey.find(params[:survey_id])
    @question = @survey.questions.new
    render :new
  end

  def create
    @survey = Survey.find(params[:survey_id])
    @question = @survey.questions.new(question_params)
    if @question.save
      redirect_to survey_path(@survey)
    else
      render :new
    end
  end

  def show
    @survey = Survey.find(params[:survey_id])
    @question = Question.find(params[:id])
    render :show
  end

  def edit
    @survey = Survey.find(params[:survey_id])
    @question = Question.find(params[:id])
    render :edit
  end

  def update
    @question = Question.find(params[:id])
    if @question.update(question_params)
      redirect_to survey_path(@question.survey)
    else
      render :edit
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to survey_path(@question.survey)
  end

  private
  def question_params
    params.require(:question).permit(:name, :answer1, :answer2, :answer3)
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController

  def index
    @surveys = Survey.all
    render :index
  end

  def new
    @survey = Survey.new
    render :new
  end

  def create
    @survey = Survey.new(survey_params)
    if @survey.save
      flash[:notice] = "Survey successfully added!"
      redirect_to surveys_path
    else
      render :new
    end
  end


  # Other controller methods go here.


  def edit
    @survey = Survey.find(params[:id])
    render :edit
  end

  def show
    @survey = Survey.find(params[:id])

    render :show
  end

  def update
    @survey= Survey.find(params[:id])
    if @survey.update(survey_params)
      redirect_to surveys_path
    else
      render :edit
    end
  end

  def destroy
    @survey = Survey.find(params[:id])
    @survey.destroy
    redirect_to surveys_path
  end

private
  def survey_params
    params.require(:survey).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_album_form.html.erb
<%= render "layouts/errors", :object => @survey %>

<%= form_for @survey do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :genre %>
  <%= f.text_field :genre %>
  <%= f.submit %>
<% end %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSurvey</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/edit.html.erb
<h1>Edit question:</h1>

<%= form_for [@survey, @question] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <p><%= f.submit %></p>
<% end %>

app/views/questions/new.html.erb
<h1>Add a new question:</h1>

<%= form_for [@survey, @question] do |f| %>

<%= f.label :Question %>
<%= f.text_field :name %>

<%= f.label :Answer %>
<%= f.text_field :answer1 %>

<%= f.label :Answer %>
<%= f.text_field :answer2 %>

<%= f.label :Answer %>
<%= f.text_field :answer3 %>

<p><%= f.submit %></p>
 
<% end %>

app/views/questions/show.html.erb
<h1>Question: <%= @question.name %></h1>
<h2>Survey: <%= @survey.name %></h2>

<h2>question: <%= @question.answer1 %></h2>

<h2>question: <%= @question.answer2 %></h2>

<h2>question: <%= @question.answer3 %></h2>


<p><%= link_to "Edit question", edit_survey_question_path(@survey, @question) %></p>
<p><%= link_to "Delete question", survey_question_path(@survey, @question),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>

<p><%= link_to "Return to survey", survey_path(@survey) %></p>

app/views/surveys/edit.html.erb
<h1>Edit survey</h1>

<%= form_for @survey do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit  %>
<% end %>

app/views/surveys/index.html.erb
<h2>We have an index!</h2>

<% if @surveys.any? %>
  <ul>
    <% @surveys.each do |survey| %>
      <li><%= link_to survey.name, survey_path(survey) %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no surveys yet.</p>
<% end %>


<p><%= link_to "Create new survey", new_survey_path %></p>

app/views/surveys/new.html.erb
<% if @survey.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% @survey.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<h1>New survey</h1>

<%= render "layouts/errors", :object => @survey %>

<%= form_for @survey do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit  %>
<% end %>

app/views/surveys/show.html.erb
<h1><%= @survey.name %></h1>

<% if @survey.questions.any? %>
  <h4>Here are the questions for this survey:</h4>

  <% @survey.questions.each do |question| %>
    <ul>
      <li>
        <%= link_to question.name, survey_question_path(@survey, question) %>
      </li>
    </ul>
  <% end %>
<% else %>
  <p>No questions are listed for this survey.</p>
<% end %>

<p><%= link_to "Add a question", new_survey_question_path(@survey) %></p>

<p><%= link_to "Edit", edit_survey_path(@survey) %></p>
<p><%= link_to "Delete survey", survey_path(@survey),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>

<p><%= link_to "Return to surveys", surveys_path %></p>